import type { ShippingOrder } from "./shippingTypes";

export const shippingOrders: ShippingOrder[] = [
  {
    id: "EXP24001",
    customer: "Amazon",
    carrier: "Chronopost",
    dock: "Quai 1",
    priority: "Haute",
    status: "Chargement",
    parcels: 84,
    pallets: 6,
    progress: 72,
    departureTime: "11:30",
  },
  {
    id: "EXP24002",
    customer: "Carrefour",
    carrier: "DHL",
    dock: "Quai 2",
    priority: "Moyenne",
    status: "Contrôle transport",
    parcels: 62,
    pallets: 4,
    progress: 88,
    departureTime: "12:15",
  },
  {
    id: "EXP24003",
    customer: "Nike",
    carrier: "Geodis",
    dock: "Quai 3",
    priority: "Basse",
    status: "En attente",
    parcels: 41,
    pallets: 3,
    progress: 12,
    departureTime: "14:00",
  },
  {
    id: "EXP24004",
    customer: "L'Oréal",
    carrier: "DB Schenker",
    dock: "Quai 4",
    priority: "Haute",
    status: "Chargement",
    parcels: 96,
    pallets: 8,
    progress: 61,
    departureTime: "11:45",
  },
  {
    id: "EXP24005",
    customer: "Samsung",
    carrier: "UPS",
    dock: "Quai 5",
    priority: "Moyenne",
    status: "Expédiée",
    parcels: 55,
    pallets: 5,
    progress: 100,
    departureTime: "09:50",
  },
];