export interface DemoStationSnapshot {
  status: string;
  ordersTotal: number;
  ordersCompleted: number;
  ordersInProgress: number;
  priorityOrders: number;
  preparedLines: number;
  preparedUnits: number;
  parcels: number;
  productivity: number;
  projectedService: number;
  warehouseHealth: number;
  receptionsActive: number;
  receptionsFinished: number;
  shipmentsReady: number;
  shipmentsConfirmed: number;
  shipmentsFinished: number;
  mailReceived: number;
  mailAwaitingReply: number;
  staffPresent: number;
  pickersActive: number;
  stockMovements: number;
  alerts: number;
}

export const demoStationSnapshots: Record<number, DemoStationSnapshot> = {
  1: {
    status: "Briefing du matin",
    ordersTotal: 526,
    ordersCompleted: 0,
    ordersInProgress: 0,
    priorityOrders: 41,
    preparedLines: 0,
    preparedUnits: 0,
    parcels: 0,
    productivity: 0,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 0,
    shipmentsReady: 0,
    shipmentsConfirmed: 0,
    shipmentsFinished: 0,
    mailReceived: 0,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 0,
    alerts: 0,
  },

  2: {
    status: "Équipes opérationnelles",
    ordersTotal: 526,
    ordersCompleted: 0,
    ordersInProgress: 18,
    priorityOrders: 41,
    preparedLines: 180,
    preparedUnits: 1120,
    parcels: 14,
    productivity: 72,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 0,
    shipmentsReady: 0,
    shipmentsConfirmed: 0,
    shipmentsFinished: 0,
    mailReceived: 0,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 0,
    alerts: 0,
  },

  3: {
    status: "Arrivage détecté",
    ordersTotal: 526,
    ordersCompleted: 9,
    ordersInProgress: 24,
    priorityOrders: 39,
    preparedLines: 510,
    preparedUnits: 3240,
    parcels: 33,
    productivity: 84,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 0,
    shipmentsReady: 2,
    shipmentsConfirmed: 0,
    shipmentsFinished: 0,
    mailReceived: 1,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 0,
    alerts: 0,
  },

  4: {
    status: "Réception en cours",
    ordersTotal: 526,
    ordersCompleted: 18,
    ordersInProgress: 29,
    priorityOrders: 36,
    preparedLines: 820,
    preparedUnits: 5140,
    parcels: 57,
    productivity: 89,
    projectedService: 99,
    warehouseHealth: 97,
    receptionsActive: 1,
    receptionsFinished: 0,
    shipmentsReady: 4,
    shipmentsConfirmed: 1,
    shipmentsFinished: 0,
    mailReceived: 1,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 0,
    alerts: 0,
  },

  5: {
    status: "Stock mis à jour",
    ordersTotal: 526,
    ordersCompleted: 31,
    ordersInProgress: 34,
    priorityOrders: 34,
    preparedLines: 1240,
    preparedUnits: 8030,
    parcels: 86,
    productivity: 95,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 1,
    shipmentsReady: 7,
    shipmentsConfirmed: 3,
    shipmentsFinished: 0,
    mailReceived: 1,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 24,
    alerts: 0,
  },

  6: {
    status: "Préparation en cadence",
    ordersTotal: 526,
    ordersCompleted: 92,
    ordersInProgress: 47,
    priorityOrders: 28,
    preparedLines: 3260,
    preparedUnits: 20540,
    parcels: 224,
    productivity: 99,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 1,
    receptionsFinished: 1,
    shipmentsReady: 18,
    shipmentsConfirmed: 9,
    shipmentsFinished: 4,
    mailReceived: 2,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 42,
    alerts: 0,
  },

  7: {
    status: "Risque sur l'objectif",
    ordersTotal: 526,
    ordersCompleted: 247,
    ordersInProgress: 62,
    priorityOrders: 31,
    preparedLines: 7120,
    preparedUnits: 44600,
    parcels: 492,
    productivity: 86,
    projectedService: 91,
    warehouseHealth: 89,
    receptionsActive: 1,
    receptionsFinished: 2,
    shipmentsReady: 39,
    shipmentsConfirmed: 25,
    shipmentsFinished: 14,
    mailReceived: 4,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 68,
    alerts: 1,
  },

  8: {
    status: "Décision recommandée",
    ordersTotal: 526,
    ordersCompleted: 254,
    ordersInProgress: 64,
    priorityOrders: 29,
    preparedLines: 7380,
    preparedUnits: 46100,
    parcels: 507,
    productivity: 87,
    projectedService: 92,
    warehouseHealth: 90,
    receptionsActive: 1,
    receptionsFinished: 2,
    shipmentsReady: 42,
    shipmentsConfirmed: 27,
    shipmentsFinished: 15,
    mailReceived: 4,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 71,
    alerts: 1,
  },

  9: {
    status: "Trajectoire rétablie",
    ordersTotal: 526,
    ordersCompleted: 334,
    ordersInProgress: 55,
    priorityOrders: 18,
    preparedLines: 9480,
    preparedUnits: 60700,
    parcels: 662,
    productivity: 108,
    projectedService: 98,
    warehouseHealth: 96,
    receptionsActive: 0,
    receptionsFinished: 3,
    shipmentsReady: 61,
    shipmentsConfirmed: 45,
    shipmentsFinished: 28,
    mailReceived: 5,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 91,
    alerts: 0,
  },

  10: {
    status: "Vague d'expéditions",
    ordersTotal: 526,
    ordersCompleted: 418,
    ordersInProgress: 43,
    priorityOrders: 11,
    preparedLines: 11840,
    preparedUnits: 76600,
    parcels: 824,
    productivity: 107,
    projectedService: 99,
    warehouseHealth: 97,
    receptionsActive: 0,
    receptionsFinished: 3,
    shipmentsReady: 78,
    shipmentsConfirmed: 63,
    shipmentsFinished: 46,
    mailReceived: 7,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 108,
    alerts: 0,
  },

  11: {
    status: "Confirmation transporteur attendue",
    ordersTotal: 526,
    ordersCompleted: 461,
    ordersInProgress: 31,
    priorityOrders: 7,
    preparedLines: 13250,
    preparedUnits: 85800,
    parcels: 918,
    productivity: 105,
    projectedService: 98,
    warehouseHealth: 94,
    receptionsActive: 0,
    receptionsFinished: 3,
    shipmentsReady: 91,
    shipmentsConfirmed: 74,
    shipmentsFinished: 58,
    mailReceived: 8,
    mailAwaitingReply: 1,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 116,
    alerts: 1,
  },

  12: {
    status: "Enlèvement sécurisé",
    ordersTotal: 526,
    ordersCompleted: 492,
    ordersInProgress: 22,
    priorityOrders: 3,
    preparedLines: 14260,
    preparedUnits: 92700,
    parcels: 986,
    productivity: 104,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 3,
    shipmentsReady: 101,
    shipmentsConfirmed: 91,
    shipmentsFinished: 74,
    mailReceived: 9,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 124,
    alerts: 0,
  },

  13: {
    status: "Journée clôturée",
    ordersTotal: 526,
    ordersCompleted: 518,
    ordersInProgress: 8,
    priorityOrders: 0,
    preparedLines: 14880,
    preparedUnits: 97200,
    parcels: 1040,
    productivity: 103,
    projectedService: 99,
    warehouseHealth: 98,
    receptionsActive: 0,
    receptionsFinished: 3,
    shipmentsReady: 0,
    shipmentsConfirmed: 0,
    shipmentsFinished: 96,
    mailReceived: 9,
    mailAwaitingReply: 0,
    staffPresent: 49,
    pickersActive: 36,
    stockMovements: 131,
    alerts: 0,
  },
};
