import type { PreparationOrder } from "./preparationTypes";

export const preparationOrders: PreparationOrder[] = [
  {
    id: "CMD24001",
    customer: "Amazon",
    picker: "Lucas",
    priority: "Haute",
    status: "En préparation",
    progress: 82,
    lines: 34,
    deadline: "10:45",
  },
  {
    id: "CMD24002",
    customer: "Carrefour",
    picker: "Emma",
    priority: "Moyenne",
    status: "Contrôle",
    progress: 94,
    lines: 21,
    deadline: "11:15",
  },
  {
    id: "CMD24003",
    customer: "Nike",
    picker: "Thomas",
    priority: "Basse",
    status: "En attente",
    progress: 12,
    lines: 18,
    deadline: "13:00",
  },
  {
    id: "CMD24004",
    customer: "L'Oréal",
    picker: "Sarah",
    priority: "Haute",
    status: "En préparation",
    progress: 63,
    lines: 42,
    deadline: "10:30",
  },
  {
    id: "CMD24005",
    customer: "Samsung",
    picker: "Mehdi",
    priority: "Moyenne",
    status: "Terminée",
    progress: 100,
    lines: 27,
    deadline: "09:50",
  },
];